//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rasef.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rasef.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action By.
        /// </summary>
        internal static string actionBy {
            get {
                return ResourceManager.GetString("actionBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Date.
        /// </summary>
        internal static string actionDate {
            get {
                return ResourceManager.GetString("actionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string actions {
            get {
                return ResourceManager.GetString("actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add BOQ Item.
        /// </summary>
        internal static string addBoqItem {
            get {
                return ResourceManager.GetString("addBoqItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Equipment.
        /// </summary>
        internal static string addEquipment {
            get {
                return ResourceManager.GetString("addEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Fix.
        /// </summary>
        internal static string addFix {
            get {
                return ResourceManager.GetString("addFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        internal static string additionalInfo {
            get {
                return ResourceManager.GetString("additionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Lane.
        /// </summary>
        internal static string addLane {
            get {
                return ResourceManager.GetString("addLane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry of Transport &amp; Logistics.
        /// </summary>
        internal static string agency {
            get {
                return ResourceManager.GetString("agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign To.
        /// </summary>
        internal static string assignTo {
            get {
                return ResourceManager.GetString("assignTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string attachments {
            get {
                return ResourceManager.GetString("attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string attachmentsTitle {
            get {
                return ResourceManager.GetString("attachmentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Home.
        /// </summary>
        internal static string backHome {
            get {
                return ResourceManager.GetString("backHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOQ Items.
        /// </summary>
        internal static string boqItems {
            get {
                return ResourceManager.GetString("boqItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Intelligence.
        /// </summary>
        internal static string businessIntelligence {
            get {
                return ResourceManager.GetString("businessIntelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Category.
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string comments {
            get {
                return ResourceManager.GetString("comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string configuration {
            get {
                return ResourceManager.GetString("configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant.
        /// </summary>
        internal static string consultant {
            get {
                return ResourceManager.GetString("consultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant Attachments.
        /// </summary>
        internal static string consultantAttachments {
            get {
                return ResourceManager.GetString("consultantAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Number.
        /// </summary>
        internal static string contractNumber {
            get {
                return ResourceManager.GetString("contractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor.
        /// </summary>
        internal static string contractor {
            get {
                return ResourceManager.GetString("contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor Attachments.
        /// </summary>
        internal static string contractorAttachments {
            get {
                return ResourceManager.GetString("contractorAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string createdDate {
            get {
                return ResourceManager.GetString("createdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Work Order.
        /// </summary>
        internal static string createWorkOrder {
            get {
                return ResourceManager.GetString("createWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Stage.
        /// </summary>
        internal static string currentStage {
            get {
                return ResourceManager.GetString("currentStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View general KPIs.
        /// </summary>
        internal static string dashboardDesc {
            get {
                return ResourceManager.GetString("dashboardDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboards.
        /// </summary>
        internal static string dashboards {
            get {
                return ResourceManager.GetString("dashboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Manager.
        /// </summary>
        internal static string departmentManager {
            get {
                return ResourceManager.GetString("departmentManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distortion.
        /// </summary>
        internal static string distortion {
            get {
                return ResourceManager.GetString("distortion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string duration {
            get {
                return ResourceManager.GetString("duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Duration Should be Estimated in Days.
        /// </summary>
        internal static string durationHelp {
            get {
                return ResourceManager.GetString("durationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise Asset Management.
        /// </summary>
        internal static string EAM {
            get {
                return ResourceManager.GetString("EAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string endDate {
            get {
                return ResourceManager.GetString("endDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string equipment {
            get {
                return ResourceManager.GetString("equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment List.
        /// </summary>
        internal static string equipmentList {
            get {
                return ResourceManager.GetString("equipmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Name.
        /// </summary>
        internal static string equipmentName {
            get {
                return ResourceManager.GetString("equipmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excavation Information.
        /// </summary>
        internal static string excavationInfo {
            get {
                return ResourceManager.GetString("excavationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excavation Notes.
        /// </summary>
        internal static string excavationNotes {
            get {
                return ResourceManager.GetString("excavationNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excavations.
        /// </summary>
        internal static string excavations {
            get {
                return ResourceManager.GetString("excavations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excavation Status.
        /// </summary>
        internal static string excavationStatus {
            get {
                return ResourceManager.GetString("excavationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Emergency.
        /// </summary>
        internal static string ExceptionEmergency {
            get {
                return ResourceManager.GetString("ExceptionEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Priority.
        /// </summary>
        internal static string ExceptionPriority {
            get {
                return ResourceManager.GetString("ExceptionPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exec Qty.
        /// </summary>
        internal static string execQty {
            get {
                return ResourceManager.GetString("execQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality.
        /// </summary>
        internal static string filterMunicipality {
            get {
                return ResourceManager.GetString("filterMunicipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string filterStatus {
            get {
                return ResourceManager.GetString("filterStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Description.
        /// </summary>
        internal static string fixDescription {
            get {
                return ResourceManager.GetString("fixDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix List.
        /// </summary>
        internal static string fixList {
            get {
                return ResourceManager.GetString("fixList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Name.
        /// </summary>
        internal static string fixName {
            get {
                return ResourceManager.GetString("fixName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow up Workflow History.
        /// </summary>
        internal static string followWorkflow {
            get {
                return ResourceManager.GetString("followWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Manager.
        /// </summary>
        internal static string generalManager {
            get {
                return ResourceManager.GetString("generalManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo Provider.
        /// </summary>
        internal static string geoProvider {
            get {
                return ResourceManager.GetString("geoProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIS.
        /// </summary>
        internal static string gis {
            get {
                return ResourceManager.GetString("gis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        internal static string goBack {
            get {
                return ResourceManager.GetString("goBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image After.
        /// </summary>
        internal static string imageAfter {
            get {
                return ResourceManager.GetString("imageAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Before.
        /// </summary>
        internal static string imageBefore {
            get {
                return ResourceManager.GetString("imageBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        internal static string itemCode {
            get {
                return ResourceManager.GetString("itemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Desc.
        /// </summary>
        internal static string itemDesc {
            get {
                return ResourceManager.GetString("itemDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixes.
        /// </summary>
        internal static string itemFix {
            get {
                return ResourceManager.GetString("itemFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items per page.
        /// </summary>
        internal static string itemsPerPage {
            get {
                return ResourceManager.GetString("itemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lane No.
        /// </summary>
        internal static string laneNo {
            get {
                return ResourceManager.GetString("laneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lane Type.
        /// </summary>
        internal static string laneType {
            get {
                return ResourceManager.GetString("laneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main District.
        /// </summary>
        internal static string mainDistrict {
            get {
                return ResourceManager.GetString("mainDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Street.
        /// </summary>
        internal static string mainStreet {
            get {
                return ResourceManager.GetString("mainStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Key.
        /// </summary>
        internal static string mapKey {
            get {
                return ResourceManager.GetString("mapKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality.
        /// </summary>
        internal static string municipality {
            get {
                return ResourceManager.GetString("municipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality Head.
        /// </summary>
        internal static string municipalityHead {
            get {
                return ResourceManager.GetString("municipalityHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No history.
        /// </summary>
        internal static string noHistory {
            get {
                return ResourceManager.GetString("noHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items.
        /// </summary>
        internal static string noItems {
            get {
                return ResourceManager.GetString("noItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found.
        /// </summary>
        internal static string noResults {
            get {
                return ResourceManager.GetString("noResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string notes {
            get {
                return ResourceManager.GetString("notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put detailed notes about the work....
        /// </summary>
        internal static string notesPlaceholder {
            get {
                return ResourceManager.GetString("notesPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the page you&apos;re looking for doesn&apos;t exist or has been moved.
        /// </summary>
        internal static string notFoundMessage {
            get {
                return ResourceManager.GetString("notFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found.
        /// </summary>
        internal static string notFoundTitle {
            get {
                return ResourceManager.GetString("notFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        internal static string orderDate {
            get {
                return ResourceManager.GetString("orderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Dates.
        /// </summary>
        internal static string orderDates {
            get {
                return ResourceManager.GetString("orderDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Document.
        /// </summary>
        internal static string otherDoc {
            get {
                return ResourceManager.GetString("otherDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string page {
            get {
                return ResourceManager.GetString("page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string parameters {
            get {
                return ResourceManager.GetString("parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pavement.
        /// </summary>
        internal static string pavement {
            get {
                return ResourceManager.GetString("pavement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Review.
        /// </summary>
        internal static string PendingReview {
            get {
                return ResourceManager.GetString("PendingReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lane Types.
        /// </summary>
        internal static string perLaneTypes {
            get {
                return ResourceManager.GetString("perLaneTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev Exec.
        /// </summary>
        internal static string prevExec {
            get {
                return ResourceManager.GetString("prevExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string previous {
            get {
                return ResourceManager.GetString("previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string project {
            get {
                return ResourceManager.GetString("project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan and track execution.
        /// </summary>
        internal static string projectDesc {
            get {
                return ResourceManager.GetString("projectDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Details.
        /// </summary>
        internal static string projectDetails {
            get {
                return ResourceManager.GetString("projectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Information.
        /// </summary>
        internal static string projectInfo {
            get {
                return ResourceManager.GetString("projectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Management.
        /// </summary>
        internal static string projectManagement {
            get {
                return ResourceManager.GetString("projectManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager.
        /// </summary>
        internal static string projectManager {
            get {
                return ResourceManager.GetString("projectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Plan.
        /// </summary>
        internal static string projectPlan {
            get {
                return ResourceManager.GetString("projectPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Ref.
        /// </summary>
        internal static string projectRef {
            get {
                return ResourceManager.GetString("projectRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string qty {
            get {
                return ResourceManager.GetString("qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remainder.
        /// </summary>
        internal static string remainder {
            get {
                return ResourceManager.GetString("remainder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string removeLane {
            get {
                return ResourceManager.GetString("removeLane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew Date.
        /// </summary>
        internal static string renewDate {
            get {
                return ResourceManager.GetString("renewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed reports and analytics.
        /// </summary>
        internal static string reportsDesc {
            get {
                return ResourceManager.GetString("reportsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        internal static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results.
        /// </summary>
        internal static string results {
            get {
                return ResourceManager.GetString("results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Request Created.
        /// </summary>
        internal static string RJI {
            get {
                return ResourceManager.GetString("RJI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string RJOB {
            get {
                return ResourceManager.GetString("RJOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excavation Permit Request Exists.
        /// </summary>
        internal static string RJOP {
            get {
                return ResourceManager.GetString("RJOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for Rasef System.
        /// </summary>
        internal static string RJOR {
            get {
                return ResourceManager.GetString("RJOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objection from Excavation.
        /// </summary>
        internal static string RJOS {
            get {
                return ResourceManager.GetString("RJOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Publishing Stage.
        /// </summary>
        internal static string RJPB {
            get {
                return ResourceManager.GetString("RJPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for Publishing.
        /// </summary>
        internal static string RJPBI {
            get {
                return ResourceManager.GetString("RJPBI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excavation Permit Exists.
        /// </summary>
        internal static string RJPP {
            get {
                return ResourceManager.GetString("RJPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Close.
        /// </summary>
        internal static string saveClose {
            get {
                return ResourceManager.GetString("saveClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Keep.
        /// </summary>
        internal static string saveKeep {
            get {
                return ResourceManager.GetString("saveKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by number or street.
        /// </summary>
        internal static string searchPlaceholder {
            get {
                return ResourceManager.GetString("searchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section No (Sub).
        /// </summary>
        internal static string sectionNo {
            get {
                return ResourceManager.GetString("sectionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector (Main).
        /// </summary>
        internal static string sector {
            get {
                return ResourceManager.GetString("sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select District --.
        /// </summary>
        internal static string selectDistrict {
            get {
                return ResourceManager.GetString("selectDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        internal static string selectFile {
            get {
                return ResourceManager.GetString("selectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Municipality --.
        /// </summary>
        internal static string selectMunicipality {
            get {
                return ResourceManager.GetString("selectMunicipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select --.
        /// </summary>
        internal static string selectType {
            get {
                return ResourceManager.GetString("selectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        internal static string showing {
            get {
                return ResourceManager.GetString("showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Location.
        /// </summary>
        internal static string siteLocation {
            get {
                return ResourceManager.GetString("siteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        internal static string stage {
            get {
                return ResourceManager.GetString("stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant.
        /// </summary>
        internal static string stageConsultant {
            get {
                return ResourceManager.GetString("stageConsultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor.
        /// </summary>
        internal static string stageContractor {
            get {
                return ResourceManager.GetString("stageContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Manager.
        /// </summary>
        internal static string stageDepartmentManager {
            get {
                return ResourceManager.GetString("stageDepartmentManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excavations.
        /// </summary>
        internal static string stageExcavations {
            get {
                return ResourceManager.GetString("stageExcavations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Director.
        /// </summary>
        internal static string stageGeneralManager {
            get {
                return ResourceManager.GetString("stageGeneralManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality Head.
        /// </summary>
        internal static string stageMayor {
            get {
                return ResourceManager.GetString("stageMayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager.
        /// </summary>
        internal static string stageProjectManager {
            get {
                return ResourceManager.GetString("stageProjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string street {
            get {
                return ResourceManager.GetString("street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Category.
        /// </summary>
        internal static string streetCategory {
            get {
                return ResourceManager.GetString("streetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Information.
        /// </summary>
        internal static string streetInfo {
            get {
                return ResourceManager.GetString("streetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Nos.
        /// </summary>
        internal static string streetNos {
            get {
                return ResourceManager.GetString("streetNos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-District.
        /// </summary>
        internal static string subDistrict {
            get {
                return ResourceManager.GetString("subDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Street.
        /// </summary>
        internal static string subStreet {
            get {
                return ResourceManager.GetString("subStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new work order information.
        /// </summary>
        internal static string subtitle_create {
            get {
                return ResourceManager.GetString("subtitle_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete information and actions view.
        /// </summary>
        internal static string subtitle_details {
            get {
                return ResourceManager.GetString("subtitle_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update work order details and save changes.
        /// </summary>
        internal static string subtitle_edit {
            get {
                return ResourceManager.GetString("subtitle_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or visit one of these pages:.
        /// </summary>
        internal static string suggestions {
            get {
                return ResourceManager.GetString("suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        internal static string systemSettings {
            get {
                return ResourceManager.GetString("systemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Network Maintenance &amp; Management.
        /// </summary>
        internal static string systemSubtitle {
            get {
                return ResourceManager.GetString("systemSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RASEF System.
        /// </summary>
        internal static string systemTitle {
            get {
                return ResourceManager.GetString("systemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Work Order.
        /// </summary>
        internal static string title_create {
            get {
                return ResourceManager.GetString("title_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Details.
        /// </summary>
        internal static string title_details {
            get {
                return ResourceManager.GetString("title_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Work Order.
        /// </summary>
        internal static string title_edit {
            get {
                return ResourceManager.GetString("title_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage and monitor all work orders.
        /// </summary>
        internal static string trackingSubtitle {
            get {
                return ResourceManager.GetString("trackingSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded By.
        /// </summary>
        internal static string uploadedBy {
            get {
                return ResourceManager.GetString("uploadedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users and permissions.
        /// </summary>
        internal static string userDesc {
            get {
                return ResourceManager.GetString("userDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string userManagement {
            get {
                return ResourceManager.GetString("userManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string viewDetails {
            get {
                return ResourceManager.GetString("viewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty.
        /// </summary>
        internal static string warranty {
            get {
                return ResourceManager.GetString("warranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty End Date.
        /// </summary>
        internal static string warrantyEndDate {
            get {
                return ResourceManager.GetString("warrantyEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty Start Date.
        /// </summary>
        internal static string warrantyStartDate {
            get {
                return ResourceManager.GetString("warrantyStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Duration.
        /// </summary>
        internal static string workDuration {
            get {
                return ResourceManager.GetString("workDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow History.
        /// </summary>
        internal static string workflowHistory {
            get {
                return ResourceManager.GetString("workflowHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow History.
        /// </summary>
        internal static string workflowHistoryTitle {
            get {
                return ResourceManager.GetString("workflowHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Progress.
        /// </summary>
        internal static string workflowProgress {
            get {
                return ResourceManager.GetString("workflowProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Orders.
        /// </summary>
        internal static string workOrder {
            get {
                return ResourceManager.GetString("workOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Date.
        /// </summary>
        internal static string workOrderDate {
            get {
                return ResourceManager.GetString("workOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage and track work orders.
        /// </summary>
        internal static string workorderDesc {
            get {
                return ResourceManager.GetString("workorderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order End Date.
        /// </summary>
        internal static string workOrderEndDate {
            get {
                return ResourceManager.GetString("workOrderEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Notes.
        /// </summary>
        internal static string workOrderNotes {
            get {
                return ResourceManager.GetString("workOrderNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order #.
        /// </summary>
        internal static string workOrderNumber {
            get {
                return ResourceManager.GetString("workOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Renew Date.
        /// </summary>
        internal static string workOrderRenewDate {
            get {
                return ResourceManager.GetString("workOrderRenewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Orders.
        /// </summary>
        internal static string workOrders {
            get {
                return ResourceManager.GetString("workOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Tracking.
        /// </summary>
        internal static string workOrderTracking {
            get {
                return ResourceManager.GetString("workOrderTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Type.
        /// </summary>
        internal static string workOrderType {
            get {
                return ResourceManager.GetString("workOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years Of Life.
        /// </summary>
        internal static string yearsOfLife {
            get {
                return ResourceManager.GetString("yearsOfLife", resourceCulture);
            }
        }
    }
}
